from app.api import (
    auth,
    avaliacoes,
    certificados,
    comunicacao,
    conteudos,
    credenciamento,
    cursos,
    dashboard,
    entregas,
    gamificacao,
    health,
    sandbox,
    scorm,
    sessoes,
    trilhas,
    usuarios,
)

__all__ = [
    "auth",
    "avaliacoes",
    "certificados",
    "comunicacao",
    "conteudos",
    "cursos",
    "dashboard",
    "entregas",
    "gamificacao",
    "health",
    "sandbox",
    "scorm",
    "sessoes",
    "trilhas",
    "usuarios",
    "credenciamento",
]
